# Dataset paths
data:
  train_dir: "data/beam_damage"
  test_dir: "data/test"
  val_split: 0.2

# Model
model:
  name: "swin_tiny_patch4_window7_224"
  pretrained: true
  num_classes: 3

# Training
training:
  batch_size: 16
  epochs: 50
  lr: 7e-5
  weight_decay: 1e-4
  scheduler: "cosine"
  T_max: 50
  seed: 42

# Augmentation
augmentation:
  # Class‐aware training transforms
  transform_A:
    - RandomBrightnessContrast:
        brightness_limit: 0.3
        contrast_limit: 0.3
        p: 0.7
    - CLAHE:
        p: 0.3
    - Rotate:
        limit: 5
        p: 0.4
    - MotionBlur:
        blur_limit: 3
        p: 0.2
    - GridDistortion:
        num_steps: 5
        distort_limit: 0.3
        p: 0.3
    - ISONoise:
        p: 0.2
    - CoarseDropout:
        max_holes: 2
        max_height: 30
        max_width: 30
        fill_value: 0
        p: 0.6
    - RandomShadow:
        p: 0.5
    - HorizontalFlip:
        p: 0.5
    - Resize:
        height: 224
        width: 224
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - ToTensorV2: {}

  transform_B:
    - Resize:
        height: 224
        width: 224
    - RandomBrightnessContrast:
        brightness_limit: 0.3
        contrast_limit: 0.3
        p: 0.5
    - Sharpen:
        alpha: [0.1, 0.3]
        lightness: [0.9, 1.0]
        p: 0.5
    - GaussianBlur:
        blur_limit: [1, 3]
        p: 0.2
    - ElasticTransform:
        alpha: 1
        sigma: 50
        alpha_affine: 20
        p: 0.2
    - HorizontalFlip:
        p: 0.5
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - ToTensorV2: {}

  transform_C:
    - MotionBlur:
        blur_limit: 3
        p: 0.2
    - HorizontalFlip:
        p: 0.5
    - Resize:
        height: 224
        width: 224
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - ToTensorV2: {}

  # Validation / test transform
  transform_test:
    - Resize:
        height: 224
        width: 224
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - ToTensorV2: {}